# Generated by Django 4.2.2 on 2023-06-23 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('courses', models.ManyToManyField(to='timetable.course')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ND1', 'ND1'), ('ND2', 'ND2'), ('HND1', 'HND1'), ('HND2', 'HND2')], default='ND1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('semester', models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2')], max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.lecturer')),
            ],
        ),
        migrations.AddField(
            model_name='lecturer',
            name='levels',
            field=models.ManyToManyField(to='timetable.level'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='semesters',
            field=models.ManyToManyField(to='timetable.semester'),
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_1', models.CharField(blank=True, max_length=100)),
                ('detail_1', models.CharField(blank=True, max_length=100)),
                ('topic_2', models.CharField(blank=True, max_length=100)),
                ('detail_2', models.CharField(blank=True, max_length=100)),
                ('topic_3', models.CharField(blank=True, max_length=100)),
                ('detail_3', models.CharField(blank=True, max_length=100)),
                ('topic_4', models.CharField(blank=True, max_length=100)),
                ('detail_4', models.CharField(blank=True, max_length=100)),
                ('topic_5', models.CharField(blank=True, max_length=100)),
                ('detail_5', models.CharField(blank=True, max_length=100)),
                ('topic_6', models.CharField(blank=True, max_length=100)),
                ('detail_6', models.CharField(blank=True, max_length=100)),
                ('topic_7', models.CharField(blank=True, max_length=100)),
                ('detail_7', models.CharField(blank=True, max_length=100)),
                ('topic_8', models.CharField(blank=True, max_length=100)),
                ('detail_8', models.CharField(blank=True, max_length=100)),
                ('topic_9', models.CharField(blank=True, max_length=100)),
                ('detail_9', models.CharField(blank=True, max_length=100)),
                ('topic_10', models.CharField(blank=True, max_length=100)),
                ('detail_10', models.CharField(blank=True, max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.lecturer')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.level')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.semester')),
            ],
        ),
    ]
